version: '3.8'
services:
  db:
    image: mysql:oracle
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cadastro
      MYSQL_USER: test
      MYSQL_PASSWORD: test@pass
      TZ: 'America/Sao_Paulo'
    volumes:
      - mysql-db:/var/lib/mysql

volumes:
  mysql-db:
